import { test, expect } from "@playwright/test";
import { readFileSync } from "node:fs";
test("QR return, actual sources, grounded responses, responsive layout, keyboard and permissions", async ({ page }) => {
  const errors: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  await page.goto("/equipment/EQP-000002");
  await expect(page).toHaveURL(/login\?next=/);
  await page.getByRole("button", { name: "Enter demo workspace" }).click();
  await expect(page).toHaveURL(/equipment\/EQP-000002$/);
  const tour = page.getByRole("dialog", { name: "Move without losing context" });
  await expect(tour).toBeVisible();
  await expect(page.locator(".tour-highlight")).toBeVisible();
  await expect(tour.getByText(/Step 1 of 7/)).toBeVisible();
  await page.screenshot({ path: "artifacts/onboarding-desktop.png", fullPage: true });
  await tour.getByRole("button", { name: "Next" }).click();
  await expect(page.getByRole("dialog", { name: "Know which asset is in scope" })).toBeVisible();
  await page.keyboard.press("ArrowLeft");
  await expect(page.getByRole("dialog", { name: "Move without losing context" })).toBeVisible();
  await tour.getByRole("button", { name: "Skip tour" }).click();
  await expect(tour).toBeHidden();
  await page.getByRole("button", { name: "Start guided tour" }).click();
  await expect(tour).toBeVisible();
  await page.keyboard.press("Escape");
  await expect(page.getByRole("button", { name: "Start guided tour" })).toBeFocused();
  await page.goto("/equipment");
  await expect(page.getByRole("heading", { name: "Explore equipment" })).toBeVisible();
  await expect(page.locator(".process-equipment-node")).toHaveCount(8);
  await expect(page.locator(".process-equipment-node").first()).toHaveAttribute("draggable", "false");
  const initialZoom = await page.locator(".process-map-zoom-value").textContent();
  await page.getByRole("button", { name: "Zoom in", exact: true }).click();
  await expect(page.locator(".process-map-zoom-value")).not.toHaveText(initialZoom!);
  await page.getByRole("button", { name: "Fit canvas", exact: true }).click();
  await page.locator('.process-equipment-node[data-equipment="EQP-000001"]').hover();
  await expect(page.getByRole("tooltip")).toBeVisible();
  await page.keyboard.press("Escape");
  await expect(page.getByRole("tooltip")).toBeHidden();
  await page.getByRole("textbox", { name: "Search equipment" }).fill("GA-1201A");
  await expect(page.locator("tbody tr")).toHaveCount(1);
  await page.getByRole("link", { name: "Open GA-1201A", exact: true }).click();
  await expect(page.getByRole("heading", { level: 1 })).toContainText("GA-1201A");
  await expect(page.getByRole("img", { name: /GA-1201A centrifugal pump/ })).toBeVisible();
  await expect.poll(() => page.getByRole("img", { name: /GA-1201A centrifugal pump/ }).evaluate(svg => svg.getBoundingClientRect().width)).toBeGreaterThan(0);
  await expect(page.getByRole("img", { name: /Original page 1/ })).toBeVisible();
  await expect.poll(() => page.getByRole("img", { name: /Original page 1/ }).evaluate((img: HTMLImageElement) => img.naturalWidth)).toBeGreaterThan(0);
  const fonts = await page.locator("body").evaluate(el => getComputedStyle(el).fontFamily);
  expect(fonts).toMatch(/Inter/);
  await page.screenshot({ path: "artifacts/workspace-desktop.png", fullPage: true });
  const split = page.getByRole("separator", { name: "Resize evidence and chat" });
  await split.focus(); await page.keyboard.press("ArrowLeft");
  await expect(split).toHaveAttribute("aria-valuenow", "58");
  await page.getByRole("button", { name: "Find the startup and priming procedure" }).click();
  await expect(page.getByText("Deterministic retrieval", { exact: true })).toBeVisible();
  await expect(page.getByText("Source awaits review", { exact: true })).toBeVisible();
  await page.locator(".citations a").first().click();
  await expect(page.locator(".user-question")).toHaveText("Find the startup and priming procedure");
  await page.getByRole("button", { name: "Equipment QR code" }).click();
  await expect(page.getByRole("dialog")).toBeVisible();
  await page.keyboard.press("Escape");
  await expect(page.getByRole("button", { name: "Equipment QR code" })).toBeFocused();
  await page.setViewportSize({ width: 1024, height: 900 });
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: "artifacts/workspace-compact.png", fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.emulateMedia({ reducedMotion: "reduce" });
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.getByRole("button", { name: "Start guided tour" }).click();
  await expect(page.getByRole("dialog", { name: "Move without losing context" })).toBeVisible();
  await page.screenshot({ path: "artifacts/onboarding-mobile.png", fullPage: true });
  await page.getByRole("dialog").getByRole("button", { name: "Skip tour" }).click();
  await page.getByRole("tab", { name: "Ask", exact: true }).click();
  await expect(page.getByRole("textbox", { name: "Ask a question" })).toBeVisible();
  await page.screenshot({ path: "artifacts/workspace-mobile.png", fullPage: true });
  await page.getByRole("tab", { name: "History", exact: true }).first().click();
  await expect(page.getByRole("heading", { name: "What happened before" })).toBeVisible();
  await page.getByLabel("Demo persona", { exact: true }).selectOption("reader");
  await expect(page.getByLabel("Demo persona", { exact: true })).toHaveValue("reader");
  const denied = await page.request.post("/api/hub", { headers: { Origin: new URL(page.url()).origin }, data: { action: "case.create", expectedRevision: 0, data: {} } });
  expect(denied.status()).toBe(403);
  await page.goto("/admin");
  await expect(page.getByText("Access unavailable", { exact: true })).toBeVisible();
  expect(errors).toEqual([]);
});

test("document API enforces lifecycle, ACLs, exact files, and session isolation", async ({ page, browser }) => {
  await page.goto("/login");
  const origin = new URL(page.url()).origin;
  const role = async (value: string) => {
    const r = await page.request.post("/api/session", { headers: { Origin: origin }, data: { role: value } }); expect(r.ok()).toBe(true);
  };
  await role("controller");
  let snapshot = await (await page.request.get("/api/hub")).json();
  const id = snapshot.state.documents[0].id;
  const run = async (action: string, data = {}, status = 200) => {
    const r = await page.request.post("/api/hub", { headers: { Origin: origin }, data: { action, id, data, expectedRevision: snapshot.state.revision } });
    expect(r.status()).toBe(status); if (r.ok()) snapshot = await r.json();
  };
  await run("document.metadata", { title: "Synthetic test metadata", number: "DEMO-TEST", owner: "Test owner", purpose: "Test only", access: "reviewers", equipmentIds: ["EQP-000001", "EQP-000002"] });
  await run("document.submit");
  await run("document.approve", { comment: "Self approval denied" }, 403);
  await role("reviewer"); await run("document.approve", { comment: "Test approval" });
  await role("controller"); await run("document.publish"); await run("document.fail_index"); await run("document.index");
  expect((await page.request.get(`/api/files/${id}`)).status()).toBe(200);
  await role("reader");
  expect((await page.request.get(`/api/files/${id}`)).status()).toBe(404);
  const current = await (await page.request.get("/api/hub")).json();
  expect(current.state.documents.some((d: { id: string }) => d.id === id)).toBe(false);
  const other = await browser.newContext();
  expect((await other.request.get(`${origin}/api/hub`)).status()).toBe(401);
  expect((await other.request.get(`${origin}/api/files/${id}`)).status()).toBe(401);
  await other.close();
  const csrf = await page.request.post("/api/session", { headers: { Origin: "https://untrusted.invalid" }, data: { role: "controller" } });
  expect(csrf.status()).toBe(403);
});

test("observation UI leads to reviewed unknown-cause closure and searchable failure memory", async ({ page }) => {
  await page.goto("/login");
  await page.getByRole("button", { name: "Enter demo workspace" }).click();
  await page.getByRole("dialog").getByRole("button", { name: "Skip tour" }).click();
  await page.getByRole("button", { name: "Report observation" }).click();
  await page.getByLabel("Short description").fill("Synthetic vibration follow-up");
  await page.getByLabel("Observed at (your local time)").fill("2026-01-01T10:00");
  await page.getByLabel("What did you observe?").fill("Synthetic test: vibration noticed during inspection.");
  await page.getByRole("button", { name: "Submit observation" }).click();
  await expect(page).toHaveURL(/\/cases$/);
  await page.getByRole("heading", { name: "Synthetic vibration follow-up" }).click();
  await expect(page.getByText("ORIGINAL OBSERVATION · PRESERVED")).toBeVisible();
  const origin = new URL(page.url()).origin;
  let snapshot = await (await page.request.get("/api/hub")).json();
  const id = snapshot.state.cases[0].id;
  const run = async (action: string, data = {}) => {
    const r = await page.request.post("/api/hub", { headers: { Origin: origin }, data: { action, id, data, expectedRevision: snapshot.state.revision } });
    expect(r.status(), await r.text()).toBe(200); snapshot = await r.json();
  };
  const role = async (value: string) => { expect((await page.request.post("/api/session", { headers: { Origin: origin }, data: { role: value } })).ok()).toBe(true); };
  await role("reviewer"); await run("case.triage"); await run("case.clarify", { comment: "Confirm operating context" });
  await role("engineer"); await run("case.respond", { comment: "Observed during routine inspection" });
  await role("reviewer"); await run("case.assign", { assignedTo: "Demo investigation team" });
  await role("engineer"); await run("case.update", { comment: "Inspection findings appended" });
  const closure = { causeStatus: "not_established", action: "Inspection performed", outcome: "Condition resolved", evidence: "Synthetic verification record", lesson: "Vibration inspection evidence retained" };
  await run("case.resolve", closure);
  await role("reviewer"); await run("case.return", { comment: "Clarify verification evidence" });
  await role("engineer"); await run("case.resolve", { ...closure, evidence: "Corrected synthetic verification record" });
  await role("reviewer"); await run("case.verify", { comment: "Outcome verified in demo; cause remains unestablished" });
  await run("case.fail_refresh");
  expect(snapshot.state.cases[0].status).toBe("verified_closed");
  expect(snapshot.state.cases[0].knowledge).toBe("failed");
  await run("case.refresh");
  expect(snapshot.state.cases[0].closures).toHaveLength(2);
  expect(snapshot.state.cases[0].cause).toBeNull();
  await page.reload();
  await expect(page.getByText("Not established", { exact: true })).toBeVisible();
  await page.screenshot({ path: "artifacts/verified-case.png", fullPage: true });
  const answer = await (await page.request.post("/api/ask", { headers: { Origin: origin }, data: { question: "vibration", equipmentId: "EQP-000001" } })).json();
  expect(answer.citations.some((c: { id: string }) => c.id === id)).toBe(true);
});

test("private upload requires real processing and review; duplicates are rejected", async ({ page }) => {
  await page.goto("/login"); const origin = new URL(page.url()).origin;
  await page.request.post("/api/session", { headers: { Origin: origin }, data: { role: "controller" } });
  let snapshot = await (await page.request.get("/api/hub")).json();
  const manifest = JSON.parse(readFileSync("data/file-manifest.json", "utf8"));
  const buffer = readFileSync(`data/files/${manifest[snapshot.state.documents[0].id].filename}`);
  const upload = async (documentId?: string) => page.request.post("/api/upload", { headers: { Origin: origin }, multipart: {
    file: { name: "synthetic-workflow-copy.pdf", mimeType: "application/pdf", buffer }, equipmentId: "EQP-000001", expectedRevision: String(snapshot.state.revision), ...(documentId ? { documentId } : {}),
  } });
  const response = await upload(); expect(response.status()).toBe(200); snapshot = await response.json();
  const doc = snapshot.state.documents[0];
  expect(doc.review).toBe("not_submitted"); expect(doc.processing).toBe("queued");
  expect((await page.request.get(`/api/files/${doc.id}`)).status()).toBe(200);
  const duplicate = await upload(doc.documentId); expect(duplicate.status()).toBe(409);
  const processed = await page.request.post("/api/hub", { headers: { Origin: origin }, data: { action: "document.process", id: doc.id, expectedRevision: snapshot.state.revision, data: { text: "Synthetic manual transcription", comment: "Manual verification for test only" } } });
  expect(processed.status()).toBe(200); snapshot = await processed.json();
  expect(snapshot.state.documents[0].processing).toBe("succeeded"); expect(snapshot.state.documents[0].review).toBe("not_submitted");
  await page.goto(`/admin/submissions/${doc.id}`);
  await expect(page.getByLabel("Document title")).toHaveValue("synthetic-workflow-copy.pdf");
});
