"use client";
import Link from "next/link";
import {useState} from "react";
import {useHub} from "./provider";
import {DocumentLibrary,Submission} from "./documents";
import {PageHeading,Status,Empty} from "./common";
import {Button} from "@/components/ui/button";
import {Textarea} from "@/components/ui/textarea";
export function Admin({section=[]}:{section?:string[]}){
 const {actor,state,capabilities,run,busy}=useHub();const [comment,setComment]=useState("");
 if(!["controller","reviewer"].includes(actor.role))return <Empty title="Access unavailable">Your account can browse its permitted sources. Document governance requires an assigned controller or reviewer role.</Empty>;
 if(section[0]==="submissions")return <Submission id={section[1]}/>;
 if(section[0]==="data-quality")return <div className="page-pad"><PageHeading eyebrow="DATA QUALITY" title="Make uncertainty visible." description="Missing metadata, failed processing, and source conflicts stay in the review queue."/><h2 className="section-title">Technical-owner review</h2>{state.issues.length?state.issues.map(i=><section className="panel-section" key={i.id}><Status tone={i.status==="open"?"amber":"green"}>{i.status}</Status><h3>{i.title}</h3><p>{i.comment}</p>{actor.role==="reviewer"&&i.status==="open"&&<><Textarea aria-label="Resolution comment" value={comment} onChange={e=>setComment(e.target.value)} placeholder="Record the resolution rationale"/><Button disabled={busy||!comment.trim()} onClick={()=>run("issue.resolve",i.id,{comment})}>Record resolution</Button></>}</section>):<Empty title="No flagged conflicts">Engineers can flag a response for technical-owner review from the evidence workspace.</Empty>}<h2 className="section-title">Sources needing attention</h2>{state.documents.filter(d=>d.metadata!=="confirmed"||d.processing==="failed"||d.indexing==="failed").map(d=><Link className="quality-row" key={d.id} href={`/admin/submissions/${d.id}`}><span>{d.title}<small className="mono">{d.number}</small></span><Status tone="amber">{d.indexing==="failed"?"Indexing failed":d.processing==="failed"?"Processing failed":"Metadata incomplete"}</Status></Link>)}</div>;
 if(section[0]==="access")return <div className="page-pad"><PageHeading eyebrow="WORKSPACE CONFIGURATION" title="Access & integrations" description="Capabilities available in this pilot environment."/><div className="detail-columns"><section className="panel-section"><h2>Your access</h2><dl className="detail-list"><dt>Account</dt><dd>{actor.name}</dd><dt>Responsibility</dt><dd>{actor.role}</dd><dt>Environment</dt><dd>{actor.mode}</dd></dl><p className="form-help">Document upload and technical approval are separate responsibilities. Demo persona switching is confined to the demo environment.</p></section><section className="panel-section"><h2>Integration status</h2><dl className="status-list">{[["Source documents",actor.mode==="demo"?"Private local files":"Private Supabase Storage"],["Search","Governed keyword retrieval"],["AI answers",capabilities.gemini?"Gemini grounded synthesis enabled":"Deterministic retrieval only"],["Supabase",actor.mode==="connected"?"Authenticated + RLS":"Not connected"],["Live measurements","Not connected"],["OCR / embeddings","Foundation only"]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl></section></div></div>;
 return <DocumentLibrary admin initialFilter={section[0]==="reviews"?"review":"all"}/>;
}
