"use client";
import Link from "next/link";
import {useState} from "react";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Textarea} from "@/components/ui/textarea";
import {useHub} from "./provider";
import {PageHeading,Status,Empty,formatDate} from "./common";
import {Report} from "./report";
export function Cases(){const {state}=useHub();return <div className="page-pad"><PageHeading eyebrow="OBSERVATIONS & FAILURE MEMORY" title="Keep the learning." description="Track reported symptoms through investigation and reviewed closure." action={<Report equipmentId="EQP-000001"/>}/><h2 className="section-title">Field observations <span>{state.cases.length}</span></h2>{!state.cases.length?<Empty title="No observations reported yet">Record a symptom from an equipment page to start an investigation.</Empty>:<div className="case-grid">{state.cases.map(c=><Link className="case-list-item" href={`/cases/${c.id}`} key={c.id}><div><span className="mono small">{state.equipment.find(e=>e.id===c.equipmentId)?.tag}</span><h3>{c.title}</h3><p>{c.symptom}</p></div><div><Status tone={c.status==="verified_closed"?"green":"amber"}>{c.status.replaceAll("_"," ")}</Status><small>{formatDate(c.observedAt)}</small></div></Link>)}</div>}<h2 className="section-title">Imported maintenance records <span>{state.history.length}</span></h2><p className="muted">Source-recorded history from the CALIBER workbook. Causes describe previous events.</p><div className="data-table-wrap"><table className="data-table"><thead><tr><th>Work order</th><th>Reported symptom</th><th>Reported date</th><th>Downtime</th></tr></thead><tbody>{state.history.map(h=><tr key={h.id}><td><Link href={`/cases/${h.id}`} className="mono">{h.wo}</Link></td><td><Link href={`/cases/${h.id}`}>{h.symptom}</Link></td><td>{formatDate(h.date)}</td><td>{h.downtime===null?"Not recorded":`${h.downtime} h`}</td></tr>)}</tbody></table></div></div>;}
export function CaseDetail({id}:{id:string}){
  const {state,actor,run,busy}=useHub();const [comment,setComment]=useState("");const [cause,setCause]=useState("not_established");
  const item=state.cases.find(c=>c.id===id);const historical=state.history.find(h=>h.id===id);const reviewer=actor.role==="reviewer";const contributor=["engineer","reviewer"].includes(actor.role);
  if(historical)return <div className="page-pad case-detail"><Link href="/cases" className="back-link">← Cases & observations</Link><PageHeading eyebrow="IMPORTED SOURCE RECORD" title={historical.wo} description={historical.symptom}/><Status>Historical evidence · training sample</Status><div className="detail-columns"><section className="panel-section"><h2>Source-recorded cause</h2><p>{historical.cause||"Not recorded"}</p><h2>Action performed</h2><p>{historical.action||"Not recorded"}</p><h2>Applicability</h2><p>This cause was recorded for a historical incident. It does not establish a diagnosis of a new symptom.</p></section><aside className="panel-section"><dl className="detail-list"><dt>Equipment</dt><dd>{state.equipment.find(e=>e.id===historical.equipmentId)?.tag ?? "Unknown equipment"}</dd><dt>Reported date</dt><dd>{formatDate(historical.date)} · source timezone unspecified</dd><dt>Downtime</dt><dd>{historical.downtime===null?"Not recorded":`${historical.downtime} hours`}</dd><dt>Total source cost</dt><dd>{historical.cost===null?"Not recorded":new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(historical.cost)}</dd><dt>Exact source locator</dt><dd className="source-path">{historical.source}</dd></dl></aside></div></div>;
  if(!item)return <Empty title="Case unavailable">Choose an accessible case from the case directory.</Empty>;
  return <div className="page-pad case-detail"><Link href="/cases" className="back-link">← Cases & observations</Link><PageHeading eyebrow={item.id} title={item.title} description={`${state.equipment.find(e=>e.id===item.equipmentId)?.tag} · ${item.type}`}/><div className="case-status-bar"><Status tone={item.status==="verified_closed"?"green":"amber"}>{item.status.replaceAll("_"," ")}</Status><Status>Knowledge refresh: {item.knowledge.replaceAll("_"," ")}</Status></div><div className="detail-columns"><div><section className="panel-section"><p className="eyebrow">ORIGINAL OBSERVATION · PRESERVED</p><p className="observation-text">{item.symptom}</p><p className="muted small">Observed {new Date(item.observedAt).toLocaleString()} · {item.reporter}<br/>Submitted {formatDate(item.submittedAt)}</p></section>{item.outcome&&<section className="panel-section"><h2>Closure proposal · revision {item.closureRevision}</h2><dl className="detail-list"><dt>Cause</dt><dd>{item.causeStatus==="established"?item.cause:"Not established"}</dd><dt>Action performed</dt><dd>{item.action}</dd><dt>Outcome</dt><dd>{item.outcome}</dd><dt>Supporting evidence</dt><dd>{item.evidence}</dd><dt>Lesson</dt><dd>{item.lesson||"Not recorded"}</dd></dl></section>}<section className="panel-section"><h2>Investigation record</h2>{item.events.map(e=><div className="audit-item" key={e.id}><strong>{e.action.replace("case.","").replaceAll("_"," ")}</strong><small>{e.actor} · {new Date(e.at).toLocaleString()}</small><p>{e.comment||"Workflow transition recorded."}</p></div>)}</section></div><aside>
    <section className="panel-section"><h2>Next action</h2><label className="form-field">Comments / findings<Textarea value={comment} onChange={e=>setComment(e.target.value)} placeholder="Record what was observed, requested, or verified."/></label><div className="action-stack">
    {reviewer&&item.status==="submitted"&&<Button disabled={busy} onClick={()=>run("case.triage",id)}>Begin triage</Button>}
    {reviewer&&item.status==="triage"&&<><Button variant="outline" disabled={busy||!comment.trim()} onClick={()=>run("case.clarify",id,{comment})}>Request clarification</Button><Button disabled={busy} onClick={()=>run("case.assign",id,{assignedTo:actor.mode==="demo"?"Demo engineering team":"Engineering team",comment})}>Assign investigation</Button></>}
    {contributor&&item.status==="awaiting_clarification"&&<Button disabled={busy||!comment.trim()} onClick={()=>run("case.respond",id,{comment})}>Submit clarification</Button>}
    {contributor&&item.status==="investigating"&&<Button variant="outline" disabled={busy||!comment.trim()} onClick={()=>run("case.update",id,{comment})}>Append findings</Button>}
    {contributor&&item.status==="closure_changes_requested"&&<Button variant="outline" disabled={busy||!comment.trim()} onClick={()=>run("case.reinvestigate",id,{comment})}>Return to investigation</Button>}
    {reviewer&&item.status==="resolved_pending_review"&&<><Button disabled={busy||!comment.trim()} onClick={()=>run("case.verify",id,{comment})}>Verify closure</Button><Button variant="outline" disabled={busy||!comment.trim()} onClick={()=>run("case.return",id,{comment})}>Return closure for correction</Button></>}
    {reviewer&&item.status==="verified_closed"&&item.knowledge!=="ready"&&<><Button disabled={busy} onClick={()=>run("case.refresh",id)}>Refresh searchable knowledge</Button>{actor.mode==="demo"&&<Button variant="outline" disabled={busy} onClick={()=>run("case.fail_refresh",id)}>Test refresh failure</Button>}</>}
    {item.status==="verified_closed"&&<p className="form-help">Closure verified. Search readiness is tracked separately; retries do not create a new case.</p>}
    {!contributor&&<p className="form-help">Your role can inspect this case. Contributor or reviewer permission is needed to update it.</p>}
    </div></section>
    {contributor&&["investigating","closure_changes_requested"].includes(item.status)&&<section className="panel-section"><h2>Document the resolution</h2><form className="stack-form" onSubmit={async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));await run("case.resolve",id,{...data,causeStatus:cause});}}><label className="form-field">Cause status<select name="causeStatus" value={cause} onChange={e=>setCause(e.target.value)}><option value="not_established">Not established</option><option value="established">Established with evidence</option></select></label>{cause==="established"&&<label className="form-field">Confirmed cause<Textarea name="cause" required defaultValue={item.cause??""}/></label>}<label className="form-field">Action performed<Textarea name="action" required defaultValue={item.action}/></label><label className="form-field">Outcome<Textarea name="outcome" required defaultValue={item.outcome}/></label><label className="form-field">Evidence / reference<Textarea name="evidence" required defaultValue={item.evidence}/></label><label className="form-field">Lesson learned<Textarea name="lesson" defaultValue={item.lesson}/></label><label className="form-field">Downtime start (optional)<Input type="datetime-local" name="downtimeStart"/></label><label className="form-field">Downtime end (optional)<Input type="datetime-local" name="downtimeEnd"/></label><p className="form-help">An unknown cause may remain unestablished. Outcome evidence and technical review are still required.</p><Button type="submit" loading={busy}>Submit closure for review</Button></form></section>}
  </aside></div></div>;
}
