"use client";
import Link from "next/link";
import { useState } from "react";
import { FileText, Upload, ArrowUpRight, Search } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Dialog, DialogTrigger, DialogPopup, DialogHeader, DialogTitle, DialogDescription, DialogPanel } from "@/components/ui/dialog";
import { useHub } from "./provider";
import { PageHeading, DocStatus, Empty, Status, formatDate } from "./common";
import { Evidence } from "./evidence";

export function UploadDialog({ documentId }: { documentId?: string }) {
  const {state, actor, busy, upload} = useHub(); const [open,setOpen] = useState(false);
  if(actor.role !== "controller") return null;
  return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger render={<Button/>}><Upload size={16}/>{documentId ? "Upload new revision" : "Upload document"}</DialogTrigger><DialogPopup><DialogHeader><DialogTitle>{documentId ? "Add an immutable revision" : "Upload a technical source"}</DialogTitle><DialogDescription>Files are stored privately. Uploading does not grant approval.</DialogDescription></DialogHeader><DialogPanel><form className="stack-form" onSubmit={async e => {e.preventDefault();const f = new FormData(e.currentTarget);if(documentId) f.set("documentId",documentId);if(await upload(f))setOpen(false);}}><label className="form-field">Equipment<select name="equipmentId">{state.equipment.map(e=><option key={e.id} value={e.id}>{e.tag} · {e.name}</option>)}</select></label><label className="upload-drop"><Upload size={25}/><strong>Select a source file</strong><span>PDF or PNG · up to 10 MB</span><Input name="file" type="file" accept="application/pdf,image/png" required/></label><p className="form-help">Confirm metadata and request technical review after processing. Existing source revisions remain available.</p><Button type="submit" loading={busy}>Upload privately</Button></form></DialogPanel></DialogPopup></Dialog>;
}
export function DocumentLibrary({admin = false, initialFilter = "all"}: {admin?: boolean; initialFilter?: string}) {
  const {state} = useHub();const [query,setQuery] = useState("");const [filter,setFilter] = useState(initialFilter);
  const docs=state.documents.filter(d=>`${d.title} ${d.number} ${d.type}`.toLowerCase().includes(query.toLowerCase()) && (filter==="all" || (filter==="review" ? d.review==="pending" : filter==="ready" ? d.indexing==="ready" : d.metadata==="incomplete")));
  return <div className="page-pad"><PageHeading eyebrow={admin ? "DOCUMENT GOVERNANCE" : "SOURCE COLLECTION"} title={admin ? "Review workspace" : "Document library"} description={admin ? "Confirm the source. Review the revision. Publish with provenance." : "Equipment-linked technical references, with every revision retained."} action={<UploadDialog/>}/><div className="list-toolbar"><div className="search-field"><Search size={16}/><Input aria-label="Search documents" placeholder="Title, document number, or type…" value={query} onChange={e=>setQuery(e.target.value)}/></div><select aria-label="Filter documents" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All documents</option><option value="metadata">Needs metadata</option><option value="review">Awaiting review</option><option value="ready">Published & indexed</option></select></div><div className="data-table-wrap"><table className="data-table"><thead><tr><th>Document</th><th>Type / revision</th><th>Technical review</th><th>Search availability</th><th/></tr></thead><tbody>{docs.map(d=><tr key={d.id}><td><Link className="document-table-link" href={admin ? `/admin/submissions/${d.id}` : `/documents/${d.documentId}/versions/${d.id}`}><FileText size={18}/><span><strong>{d.title}</strong><small className="mono">{d.number}</small></span></Link></td><td><span>{d.type.replaceAll("_"," ")}</span><small>Rev {d.revision ?? "not recorded"}</small></td><td><DocStatus doc={d}/></td><td><Status tone={d.indexing==="ready" ? "green" : d.indexing==="failed" ? "red" : "neutral"}>{d.indexing.replaceAll("_"," ")}</Status></td><td><Link href={admin ? `/admin/submissions/${d.id}` : `/documents/${d.documentId}/versions/${d.id}`} aria-label={`Open ${d.title}`}><ArrowUpRight size={17}/></Link></td></tr>)}</tbody></table></div>{!docs.length&&<Empty title="No matching documents">Try another filter or document identifier.</Empty>}<p className="collection-note">SOURCE INTEGRITY<span>Original files are retained. Source approval printed on a training document is separate from review in this hub.</span></p></div>;
}
export function Submission({id}: {id:string}) {
  const {state,actor,run,busy}=useHub();const doc=state.documents.find(d=>d.id===id);const [comment,setComment]=useState("");
  if(!doc) return <Empty title="Submission unavailable">Choose a source from the review workspace.</Empty>;
  const controller=actor.role==="controller"; const reviewer=actor.role==="reviewer";
  return <div className="page-pad"><Link href="/admin" className="back-link">← Review workspace</Link><PageHeading eyebrow={doc.id} title={doc.title} action={<UploadDialog documentId={doc.documentId}/>}/><div className="governance-layout"><div><Evidence doc={doc}/></div><aside className="governance-panel"><div className="panel-section"><h2>Revision lifecycle</h2><dl className="status-list">{[["File upload","complete"],["Processing",doc.processing],["Metadata",doc.metadata],["Technical review",doc.review],["Publication",doc.publication],["Search index",doc.indexing],["Applicability",doc.applicability]].map(([k,v])=><div key={k}><dt>{k}</dt><dd><Status tone={v==="failed"?"red":v==="approved"||v==="ready"?"green":"neutral"}>{v.replaceAll("_"," ")}</Status></dd></div>)}</dl></div><div className="panel-section"><h2>Source metadata</h2><form key={`${doc.id}-${doc.metadata}`} className="stack-form" onSubmit={async e=>{e.preventDefault();const form = new FormData(e.currentTarget);await run("document.metadata",doc.id,{...Object.fromEntries(form),equipmentIds:form.getAll("equipmentIds")});}}><label className="form-field">Document title<Input name="title" defaultValue={doc.title} required disabled={!controller||doc.review==="approved"}/></label><label className="form-field">Document number<Input name="number" defaultValue={doc.number} required disabled={!controller||doc.review==="approved"}/></label><label className="form-field">Source revision<Input name="revision" defaultValue={doc.revision??""} placeholder="Leave blank if not recorded" disabled={!controller||doc.review==="approved"}/></label><label className="form-field">Technical owner<Input name="owner" defaultValue={doc.owner} required disabled={!controller||doc.review==="approved"}/></label><label className="form-field">Purpose / change summary<Textarea name="purpose" defaultValue={doc.purpose} required disabled={!controller||doc.review==="approved"}/></label><fieldset className="equipment-link-fields" disabled={!controller||doc.review==="approved"}><legend>Applicable equipment</legend>{state.equipment.map(e=><label key={e.id}><input type="checkbox" name="equipmentIds" value={e.id} defaultChecked={doc.equipmentIds.includes(e.id)}/><span>{e.tag}</span></label>)}</fieldset><label className="form-field">Access classification<select name="access" defaultValue={doc.access} disabled={!controller||doc.review==="approved"}><option value="team">Workspace team</option><option value="reviewers">Controllers and reviewers only</option></select></label>{controller&&doc.review!=="approved"&&<Button type="submit" loading={busy}>Confirm metadata</Button>}</form></div><div className="panel-section"><h2>Next action</h2><label className="form-field">Review / action comments<Textarea value={comment} onChange={e=>setComment(e.target.value)} placeholder="Explain your decision or the required correction."/></label><div className="action-stack">
    {controller&&["not_submitted","changes_requested"].includes(doc.review)&&<Button disabled={busy||doc.metadata!=="confirmed"||doc.processing!=="succeeded"} onClick={()=>run("document.submit",id)}>Submit for technical review</Button>}
    {reviewer&&doc.review==="pending"&&<><Button disabled={busy||!comment.trim()} onClick={()=>run("document.approve",id,{comment})}>Approve this revision</Button><Button variant="outline" disabled={busy||!comment.trim()} onClick={()=>run("document.return",id,{comment})}>Return for correction</Button></>}
    {controller&&doc.review==="approved"&&doc.publication==="unpublished"&&<Button disabled={busy} onClick={()=>run("document.publish",id)}>Publish approved revision</Button>}
    {controller&&doc.publication==="published"&&doc.indexing!=="ready"&&<><Button disabled={busy} onClick={()=>run("document.index",id)}>Build search index</Button>{actor.mode==="demo"&&<Button variant="outline" disabled={busy} onClick={()=>run("document.fail_index",id)}>Test indexing failure</Button>}</>}
    {controller&&doc.publication==="published"&&<Button variant="outline" disabled={busy||!comment.trim()} onClick={()=>run("document.withdraw",id,{comment})}>Withdraw revision</Button>}
    {doc.processing!=="succeeded"&&controller&&<form className="stack-form" onSubmit={async e=>{e.preventDefault();await run("document.process",id,Object.fromEntries(new FormData(e.currentTarget)));}}><p className="form-help">Automatic extraction is not configured. Transcribe the original source below to complete manual processing. This does not approve its contents.</p><label className="form-field">Source transcription<Textarea name="text" required maxLength={12000} rows={8}/></label><label className="form-field">Processing provenance<Input name="comment" required placeholder="Source pages and transcription method"/></label><Button type="submit" disabled={busy}>Save manual extraction</Button><Button type="button" variant="outline" disabled={busy||!comment.trim()} onClick={()=>run("document.fail_process",id,{comment})}>Record processing failure</Button></form>}
    {doc.processing!=="succeeded"&&!controller&&<p className="form-help">A controller must complete processing before review.</p>}
    {!controller&&!reviewer&&<p className="form-help">A controller or reviewer is required to change this submission.</p>}
    </div></div><div className="panel-section"><h2>Revision activity</h2>{doc.events.length?doc.events.map(event=><div key={event.id} className="audit-item"><strong>{event.action.replace("document.","").replaceAll("_"," ")}</strong><small>{event.actor} · {formatDate(event.at)}</small><p>{event.comment}</p></div>):<p className="muted">Imported from the supplied training collection. No Hub review has been recorded.</p>}</div></aside></div></div>;
}
