"use client";
import { useState } from "react";
import { safeReturnPath } from "@/lib/domain/navigation";
import { BookOpen, ArrowRight, FileText, Link2, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
export function Login({ mode }: { mode: string }) {
  const [role, setRole] = useState("engineer"); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  return <main className="login-screen"><section className="login-story"><div className="brand"><span className="brand-symbol"><BookOpen size={22}/></span><span>Knowledge<span className="brand-sub">MANUFACTURING HUB</span></span></div><div className="login-intro"><p className="eyebrow">ENGINEERING KNOWLEDGE, CONNECTED</p><h1>Every answer.<br/>Back to its source.</h1><p>Your equipment documents, field observations, and maintenance experience. One traceable workspace.</p></div><div className="login-evidence"><span className="mono">GA-1201A</span><span>Hexane Feed Pump</span><div><FileText size={18}/>Technical references <span>12 sources</span></div><div><Link2 size={18}/>Maintenance memory <span>26 records</span></div><div><ShieldCheck size={18}/>Human-reviewed knowledge <span>Source first</span></div></div><footer>CALIBER 2026 <span>Case 01 / Manufacturing Knowledge Hub</span></footer></section><section className="login-form-section"><div className="login-form"><p className="eyebrow">WELCOME TO THE WORKSPACE</p><h2>{mode === "demo" ? "Explore the pilot." : "Sign in."}</h2><p className="muted">{mode === "demo" ? "A working demonstration built around the GA-1201A source collection. Choose a role to begin." : "Use your authorized engineering account."}</p><form onSubmit={async e => { e.preventDefault(); setBusy(true); setError(""); const f = new FormData(e.currentTarget); try { const r = await fetch("/api/session", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(mode === "demo" ? { role } : { email: f.get("email"), password: f.get("password") }) }); const body = await r.json(); if (!r.ok) throw new Error(body.error); const target = new URLSearchParams(window.location.search).get("next"); window.location.assign(safeReturnPath(target)); } catch(err) { setError(err instanceof Error ? err.message : "Sign-in failed."); } finally { setBusy(false); } }}>
    {mode === "demo" ? <fieldset className="persona-options"><legend>Demo persona</legend>{[["engineer", "Engineer", "Find evidence and report observations"], ["controller", "Document controller", "Manage metadata and publication"], ["reviewer", "Technical reviewer", "Review sources and verify cases"], ["reader", "Read-only engineer", "Browse accessible evidence"]].map(([id, title, description]) => <label key={id} className={role === id ? "selected" : ""}><input type="radio" name="role" value={id} checked={role === id} onChange={() => setRole(id)}/><span><strong>{title}</strong><small>{description}</small></span></label>)}</fieldset> : <><label className="form-field">Email<Input name="email" type="email" required autoComplete="username"/></label><label className="form-field">Password<Input name="password" type="password" required autoComplete="current-password"/></label></>}
    {error && <p className="error-text" role="alert">{error}</p>}<Button className="login-submit" size="lg" type="submit" loading={busy} disabled={mode === "setup"}>{mode === "demo" ? "Enter demo workspace" : "Sign in"}<ArrowRight size={16}/></Button></form><p className="login-note">{mode === "demo" ? "Training/sample data only. Persona selection simulates permissions; it is not a production login. Gemini runs only when explicitly enabled; no live sensor connection." : "Demo personas are disabled in connected mode. Configure HUB_MODE and contact your administrator for access."}</p></div></section></main>;
}
