"use client";
import Link from "next/link";
import Image from "next/image";
import { usePathname, useRouter } from "next/navigation";
import { BookOpenText, Bot, Boxes, ChevronDown, CircleHelp, ClipboardList, Ellipsis, Files, FileText, FlaskConical, FolderCheck, Gauge, LogOut, PanelLeftClose, PanelLeftOpen, ScanLine, Search, ShieldCheck, X, RefreshCw } from "lucide-react";
import { useState, type ReactNode } from "react";
import { Button } from "@/components/ui/button";
import { useHub } from "./provider";
import { Onboarding } from "./onboarding";
import { GlobalAI } from "./global-ai";
import { FloatingCandra } from "./floating-candra";
export function Shell({ children, initialCandraScope }: { children: ReactNode; initialCandraScope: string }) {
  const { actor, state, notice, setNotice, reload } = useHub(); const pathname = usePathname(); const router = useRouter(); const [collapsed, setCollapsed] = useState(false); const [knowledgeOpen, setKnowledgeOpen] = useState(pathname.startsWith("/knowledge-base")); const [mobileMoreOpen, setMobileMoreOpen] = useState(false);
  const admin = actor.role === "controller" || actor.role === "reviewer";
  const knowledgeExpanded = knowledgeOpen || pathname.startsWith("/knowledge-base");
  async function changeRole(role: string) { const r = await fetch("/api/session", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ role }) }); if (r.ok) { router.push("/equipment"); router.refresh(); } else setNotice("Persona switch failed."); }
  return <div className={`hub-app ${collapsed ? "nav-collapsed" : ""}`}>
    <a className="skip-link" href="#main-content">Skip to workspace</a>
    <aside className="hub-nav" data-tour="primary-nav"><Link href="/equipment" className="brand" aria-label="Chandra Asri Knowledge Hub"><span className="brand-symbol"><Image className="brand-logo" src="/logo-square.png" width={36} height={36} alt="" priority/></span><span className="nav-copy">Chandra Asri<span className="brand-sub">KNOWLEDGE HUB</span></span></Link>
      <div className="nav-group-label nav-copy">WORKSPACE</div><nav aria-label="Workspace navigation">
        <Nav href="/equipment" icon={<Boxes size={18}/>} active={pathname.startsWith("/equipment") && pathname !== "/equipment/what-if"} label="Equipment"/>
        <NavAction icon={<Bot size={18}/>} label="AI" ariaLabel="Open AI assistant" onClick={() => window.dispatchEvent(new CustomEvent("knowledge-hub:open-ai"))}/>
        <Nav href="/scan" icon={<ScanLine size={18}/>} active={pathname === "/scan"} label="Scan QR"/>
        <div className="nav-tree" data-open={knowledgeExpanded}>
          <button type="button" className="nav-link nav-parent" aria-expanded={knowledgeExpanded} aria-controls="knowledge-base-navigation" title="Knowledge Base" onClick={() => { if (collapsed) { setCollapsed(false); setKnowledgeOpen(true); } else setKnowledgeOpen(value => !value); }}><BookOpenText size={18}/><span className="nav-copy">Knowledge Base</span><ChevronDown className="nav-copy nav-parent-chevron" size={14}/></button>
          {knowledgeExpanded && <div className="nav-subnav nav-copy" id="knowledge-base-navigation"><Nav href="/knowledge-base/extracted-text" icon={<FileText size={14}/>} active={pathname === "/knowledge-base/extracted-text"} label="Extracted Text"/><Nav href="/knowledge-base/parameters" icon={<Gauge size={14}/>} active={pathname === "/knowledge-base/parameters"} label="Parameters"/></div>}
        </div>
        <Nav href="/equipment/what-if" icon={<FlaskConical size={18}/>} active={pathname === "/equipment/what-if"} label="What If"/>
        <Nav href="/documents" icon={<Files size={18}/>} active={pathname.startsWith("/documents")} label="Document library"/>
        <Nav href="/cases" icon={<ClipboardList size={18}/>} active={pathname.startsWith("/cases")} label="Cases & observations"/>
        {admin && <div data-tour="governance-nav"><div className="nav-group-label nav-copy">GOVERNANCE</div><Nav href="/admin" icon={<FolderCheck size={18}/>} active={pathname === "/admin"} label="Review workspace"/><Nav href="/admin/data-quality" icon={<ShieldCheck size={18}/>} active={pathname === "/admin/data-quality"} label="Data quality"/><Nav href="/admin/access" icon={<Gauge size={18}/>} active={pathname === "/admin/access"} label="Access & integration"/></div>}
      </nav><div className="nav-bottom"><div className="nav-context nav-copy"><span className="tiny-label">PILOT COLLECTION</span><strong>CALIBER · Case 01</strong><span>{state.equipment.length} equipment identities<br/>Set 01 sources available</span></div><button className="nav-collapse" onClick={() => setCollapsed(!collapsed)} aria-label={collapsed ? "Expand navigation" : "Collapse navigation"}>{collapsed ? <PanelLeftOpen size={17}/> : <PanelLeftClose size={17}/>}<span className="nav-copy">Collapse navigation</span></button></div>
    </aside><div className="hub-main"><header className="global-header"><div className="breadcrumb-line"><span>Manufacturing</span><span>/</span><strong>{pathname.startsWith("/admin") ? "Document governance" : pathname.startsWith("/knowledge-base") ? "Knowledge base" : pathname === "/equipment/what-if" ? "Scenario workspace" : "Engineering workspace"}</strong></div><div className="header-actions"><Link href="/equipment" aria-label="Search equipment"><Search size={17}/></Link><button className="global-ai-header-cta" aria-label="Ask AI" onClick={() => window.dispatchEvent(new CustomEvent("knowledge-hub:open-ai"))}><Bot size={16}/><span>Ask AI</span></button><button aria-label="Start guided tour" title="Tour this page" onClick={() => window.dispatchEvent(new Event("knowledge-hub:start-tour"))}><CircleHelp size={17}/></button><span className="header-divider"/><span className="avatar">{actor.name.slice(0,1)}</span><span className="user-name">{actor.name.split(" · ")[0]}</span><button aria-label="Sign out" onClick={async () => { await fetch("/api/session", { method: "DELETE" }); router.replace("/login"); router.refresh(); }}><LogOut size={15}/></button></div></header>
      <div className="demo-strip"><span><i/> {actor.mode === "demo" ? "DEMO WORKSPACE" : "CONNECTED WORKSPACE"}</span><span className="demo-description">{actor.mode === "demo" ? "Training data. No live telemetry; Gemini is optional." : "Supabase authenticated · permissions enforced server-side."}</span>{actor.mode === "demo" && <label className="persona-label" data-tour="persona-switch">Demo persona<select aria-label="Demo persona" value={actor.role} onChange={e => changeRole(e.target.value)}><option value="engineer">Field Operator</option><option value="reader">Field Observer · read-only</option><option value="controller">Control Room Admin</option><option value="reviewer">Technical Reviewer</option></select></label>}</div>
      {notice && <div className="notice" role="status"><span>{notice}</span><div><Button variant="ghost" size="icon-sm" aria-label="Refresh workspace" onClick={reload}><RefreshCw size={14}/></Button><Button variant="ghost" size="icon-sm" aria-label="Dismiss notification" onClick={() => setNotice("")}><X size={14}/></Button></div></div>}
      <main id="main-content" className="content-region">{children}</main>
      {mobileMoreOpen && <div className="mobile-more-backdrop" onClick={() => setMobileMoreOpen(false)}><aside className="mobile-more-sheet" role="dialog" aria-modal="true" aria-label="More workspace destinations" onClick={event => event.stopPropagation()}><header><div><span>WORKSPACE</span><strong>More destinations</strong></div><button type="button" aria-label="Close workspace menu" onClick={() => setMobileMoreOpen(false)}><X/></button></header><nav><Link href="/knowledge-base/extracted-text" onClick={() => setMobileMoreOpen(false)}><FileText/><span><strong>Extracted Text</strong><small>Continuous parsed corpus</small></span></Link><Link href="/knowledge-base/parameters" onClick={() => setMobileMoreOpen(false)}><Gauge/><span><strong>Parameters</strong><small>Structured equipment registry</small></span></Link><Link href="/documents" onClick={() => setMobileMoreOpen(false)}><Files/><span><strong>Document library</strong><small>Source files and versions</small></span></Link>{admin && <Link href="/admin" onClick={() => setMobileMoreOpen(false)}><FolderCheck/><span><strong>Review workspace</strong><small>Governance and publication</small></span></Link>}</nav></aside></div>}
      <nav className="mobile-bottom-nav" aria-label="Mobile workspace navigation"><Link href="/equipment" data-active={pathname === "/equipment"}><Boxes/><span>Overview</span></Link><Link href="/cases" data-active={pathname.startsWith("/cases")}><ClipboardList/><span>Tasks</span></Link><Link className="mobile-scan-action" href="/scan" data-active={pathname === "/scan"}><ScanLine/><span>Scan</span></Link><button type="button" onClick={() => window.dispatchEvent(new CustomEvent("knowledge-hub:open-ai"))}><Bot/><span>AI</span></button><button type="button" aria-expanded={mobileMoreOpen} data-active={pathname.startsWith("/admin") || pathname.startsWith("/documents") || pathname.startsWith("/knowledge-base")} onClick={() => setMobileMoreOpen(true)}><Ellipsis/><span>More</span></button></nav>
    </div><Onboarding key={pathname} actor={actor}/><GlobalAI initialEquipmentId={initialCandraScope}/><FloatingCandra/></div>;
}
function Nav({ href, icon, label, active }: { href: string; icon: ReactNode; label: string; active: boolean }) { return <Link href={href} className={`nav-link ${active ? "active" : ""}`} aria-current={active ? "page" : undefined} title={label}>{icon}<span className="nav-copy">{label}</span></Link>; }
function NavAction({ icon, label, ariaLabel, onClick }: { icon: ReactNode; label: string; ariaLabel: string; onClick: () => void }) { return <button type="button" className="nav-link nav-action" aria-label={ariaLabel} title={label} onClick={onClick}>{icon}<span className="nav-copy">{label}</span></button>; }
