"use client";
import Link from "next/link";
import { useRef, useState, type CSSProperties } from "react";
import Image from "next/image";
import { ArrowUp, ArrowUpRight, BookOpen, ChevronDown, ClipboardCheck, FileText, MapPin, MessageSquare, QrCode, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Dialog, DialogTrigger, DialogPopup, DialogHeader, DialogTitle, DialogDescription, DialogPanel } from "@/components/ui/dialog";
import { Tabs, TabsList, TabsTab } from "@/components/ui/tabs";
import type { Answer } from "@/lib/domain/types";
import { useHub } from "./provider";
import { Empty, Status, formatDate } from "./common";
import { Evidence } from "./evidence";
import { Report } from "./report";
import { EquipmentVisual } from "./equipment-visual";

export function Workspace({ equipmentId }: { equipmentId: string }) {
  const { state, setNotice, run, actor } = useHub(); const equipment = state.equipment.find(e => e.id === equipmentId);
  const docs = state.documents.filter(d => d.equipmentIds.includes(equipmentId));
  const [selected, setSelected] = useState(docs.find(d => d.type === "DATASHEET")?.id ?? docs[0]?.id ?? "");
  const [view, setView] = useState("documents"); const [mobile, setMobile] = useState("documents");
  const [expanded, setExpanded] = useState(false); const [query, setQuery] = useState(""); const [broad, setBroad] = useState(false);
  const [messages, setMessages] = useState<{ question: string; answer: Answer; finished?: boolean }[]>([]); const [asking, setAsking] = useState(false); const [split, setSplit] = useState(60);
  const splitRef = useRef<HTMLDivElement>(null); const inputRef = useRef<HTMLInputElement>(null);
  if (!equipment) return <Empty title="Equipment unavailable">Return to the equipment directory.</Empty>;
  const lastReport = state.cases.find(c => c.equipmentId === equipmentId);
  const chosen = docs.find(d => d.id === selected);
  async function ask(question: string) {
    if (!question.trim()) return; setAsking(true); setQuery("");
    try { const history = messages.slice(-3).map(message => ({ question: message.question, answer: message.answer.text })); const r = await fetch("/api/ask", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ question, equipmentId, broad, history }) }); const answer = await r.json(); if (!r.ok) throw new Error(answer.error); setMessages(old => [...old, { question, answer }]); if (answer.view === "history") setView("history"); else if (answer.view) { setSelected(answer.view); setView("documents"); } }
    catch(e) { setNotice(e instanceof Error ? e.message : "Question could not be processed."); } finally { setAsking(false); }
  }
  return <div className="equipment-workspace"><div className="equipment-heading" data-tour="equipment-context"><div className="equipment-identity"><EquipmentVisual equipment={equipment} variant="compact"/><div><div className="equipment-eyebrow"><Link href="/equipment">Equipment</Link><span>/</span><span>Set {equipment.set}</span></div><h1><span className="mono">{equipment.tag}</span><span>{equipment.name}</span></h1><p><MapPin size={13}/>{equipment.location || "Location not recorded"}<span className="dot-divider">·</span>{equipment.area}</p></div></div><div className="equipment-actions" data-tour="equipment-actions"><Dialog><DialogTrigger render={<Button variant="outline" size="icon" aria-label="Equipment QR code"/>}><QrCode size={17}/></DialogTrigger><DialogPopup><DialogHeader><DialogTitle>Equipment access</DialogTitle><DialogDescription>{equipment.tag} · permanent equipment page</DialogDescription></DialogHeader><DialogPanel><Image src={`/api/qr?equipment=${equipmentId}`} width={240} height={240} alt={`QR code for ${equipment.tag}`} unoptimized className="qr-image"/><p className="form-help">Scan with a device that can reach this website. Sign-in and equipment permissions still apply. QR identifies this asset; it does not measure its condition.</p><Button variant="outline" onClick={() => navigator.clipboard.writeText(`${window.location.origin}/equipment/${equipmentId}`).then(() => setNotice("Equipment link copied."))}>Copy equipment link</Button></DialogPanel></DialogPopup></Dialog><FieldReading equipmentId={equipmentId}/><Report equipmentId={equipmentId}/></div></div>
    <div className="condition-strip"><span className="condition-label">LAST REPORTED CONDITION</span><span>{lastReport ? lastReport.title : "No condition reported"}</span>{lastReport ? <><Status tone="amber">{lastReport.status.replaceAll("_", " ")}</Status><span className="muted">{formatDate(lastReport.observedAt)} · {lastReport.reporter}</span></> : <span className="muted">No live measurements connected</span>}</div>
    <div className="mobile-workspace-tabs"><Tabs value={mobile} onValueChange={v => {setMobile(String(v)); if(v === "history") setView("history"); if(v === "documents") setView("documents");}}><TabsList><TabsTab value="documents">Documents</TabsTab><TabsTab value="ask">Ask</TabsTab><TabsTab value="history">History</TabsTab></TabsList></Tabs></div>
    <div className={`workspace-split mobile-${mobile}`} ref={splitRef} style={{ "--evidence-share": `${split}%` } as CSSProperties}>
      <div className="left-workspace" data-tour="evidence-workspace"><div className="pane-heading"><div><BookOpen size={16}/><strong>Evidence workspace</strong></div><Tabs value={view} onValueChange={v => setView(String(v))}><TabsList variant="underline"><TabsTab value="documents">Documents</TabsTab><TabsTab value="history">History</TabsTab></TabsList></Tabs></div>
        {view === "history" ? <div className="history-pane"><HistoryList equipmentId={equipmentId}/></div> : <Evidence key={chosen?.id} doc={chosen} compact/>}
        <div className={`document-drawer ${expanded ? "expanded" : ""}`} data-tour="related-sources"><button className="drawer-toggle" onClick={() => setExpanded(!expanded)} aria-expanded={expanded}><span>RELATED DOCUMENTS <b>{docs.length}</b></span><span>{expanded ? "Collapse" : "Expand documents"}<ChevronDown size={15}/></span></button><div className="document-items">{docs.map(doc => <button key={doc.id} className={`document-item ${selected === doc.id ? "selected" : ""}`} onClick={() => { setSelected(doc.id); setView("documents"); }}><FileText size={17}/><span><strong>{doc.title}</strong><small>{doc.type.replaceAll("_", " ")} · Rev {doc.revision ?? "—"}</small></span><ArrowUpRight size={14}/></button>)}</div></div>
      </div><div className="split-handle" role="separator" aria-label="Resize evidence and chat" aria-orientation="vertical" aria-valuenow={split} aria-valuemin={40} aria-valuemax={72} tabIndex={0} onKeyDown={e => {if(e.key === "ArrowLeft" || e.key === "ArrowRight") {e.preventDefault();setSplit(s => Math.max(40, Math.min(72, s + (e.key === "ArrowLeft" ? -2 : 2))));}}} onPointerDown={e => { e.currentTarget.setPointerCapture(e.pointerId); }} onPointerMove={e => { if (e.currentTarget.hasPointerCapture(e.pointerId) && splitRef.current) { const rect = splitRef.current.getBoundingClientRect(); setSplit(Math.max(40, Math.min(72, (e.clientX - rect.left) / rect.width * 100))); } }}><span/></div>
      <section className="chat-pane" aria-label="Knowledge assistant" data-tour="knowledge-assistant"><div className="pane-heading"><div><MessageSquare size={16}/><strong>Ask the knowledge hub</strong></div><span className="tiny-label">{actor.mode === "demo" ? "DEMO" : "GROUNDED"}</span></div><div className="chat-scope"><span>SEARCH SCOPE</span><select aria-label="Search scope" value={broad ? "all" : "asset"} onChange={e => setBroad(e.target.value === "all")}><option value="asset">{equipment.tag} · this equipment</option><option value="all">All accessible equipment</option></select></div>
        <div className="conversation" aria-live="polite">{messages.length === 0 ? <div className="chat-welcome"><span className="assistant-mark"><BookOpen size={23}/></span><h2>Start with a question.<br/>Follow the evidence.</h2><p>Explore technical references and past maintenance records for <strong>{equipment.tag}</strong>.</p><div className="suggested-questions">{["Find the startup and priming procedure", "Show previous vibration-related failures", "Where is this equipment located?", "Show a measured temperature trend"].map(q => <button key={q} onClick={() => ask(q)} disabled={asking}>{q}<ArrowUpRight size={14}/></button>)}</div><p className="assistant-note"><ShieldCheck size={14}/>Every source keeps its revision and review status.</p></div> : messages.map((message, index) => { const sourceIds = message.answer.citations.filter(c => docs.some(d => d.id === c.id)).map(c => c.id); return <article className="chat-turn" key={index}><div className="user-question">{message.question}</div><div className="answer-brand"><BookOpen size={15}/>Knowledge hub<span>{message.answer.provider ?? "Deterministic retrieval"}</span></div><Status tone={message.answer.conflict ? "red" : message.answer.citations.length ? "amber" : "neutral"}>{message.answer.label}</Status><p>{message.answer.text}</p><div className="answer-evidence"><span className="tiny-label">SUPPORTING EVIDENCE</span><p>{message.answer.evidence}</p></div><div className="citations">{message.answer.citations.map((c, n) => <a key={c.id} href={c.href} target="_blank" rel="noreferrer" onClick={e => { if (docs.some(d => d.id === c.id)) { e.preventDefault(); setSelected(c.id); setView("documents"); setMobile("documents"); } }}><span className="citation-number">{n+1}</span><span><strong>{c.label}</strong><small>{c.locator}</small></span><ArrowUpRight size={14}/></a>)}</div><p className="answer-limitation">{message.answer.limitations}</p><div className="answer-actions"><button onClick={() => inputRef.current?.focus()}>Refine question</button>{actor.role !== "reader" && sourceIds.length > 0 && <button onClick={() => run("issue.create", undefined, {title: `Review: ${message.question}`, comment: "Engineer requested technical-owner review of this response.", sourceIds})}>Flag for review</button>}<button onClick={() => setMessages(old => old.map((m, i) => i === index ? {...m, finished: true} : m))}>{message.finished ? (message.answer.citations.length ? "Source inspected" : "Request unresolved") : "Finish inspection"}</button></div></article>; })}{asking && <p className="muted">Finding accessible sources…</p>}</div>
        <form className="chat-composer" onSubmit={e => {e.preventDefault();ask(query);}}><div><Input ref={inputRef} aria-label="Ask a question" value={query} onChange={e => setQuery(e.target.value)} placeholder={`Ask about ${equipment.tag}…`} maxLength={2000}/><Button type="submit" size="icon" aria-label="Send question" disabled={!query.trim() || asking}><ArrowUp size={17}/></Button></div><small>Decision support · verify sources before acting</small></form>
      </section></div></div>;
}
function FieldReading({ equipmentId }: { equipmentId: string }) {
  const { state, actor, busy, run } = useHub(); const parameters = (state.parameters ?? []).filter(item => item.equipmentId === equipmentId); const [parameterId, setParameterId] = useState(parameters[0]?.id ?? "");
  if (!parameters.length || !["engineer", "reviewer"].includes(actor.role)) return null;
  const selected = parameters.find(item => item.id === parameterId) ?? parameters[0];
  return <Dialog><DialogTrigger render={<Button variant="outline"/>}><ClipboardCheck size={15}/> Field check</DialogTrigger><DialogPopup><DialogHeader><DialogTitle>Record field reading</DialogTitle><DialogDescription>Manual observation for {state.equipment.find(item => item.id === equipmentId)?.tag}. This does not change governed limits.</DialogDescription></DialogHeader><DialogPanel><form className="stack-form" onSubmit={async event => { event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget)); await run("parameter.reading", parameterId, data); }}><label className="form-field">Parameter<select value={parameterId} onChange={event => setParameterId(event.target.value)}>{parameters.map(item => <option value={item.id} key={item.id}>{item.instrumentTag} · {item.name}</option>)}</select></label><label className="form-field">Observed value ({selected.unit || "unitless"})<Input name="currentValue" type="number" step="any" required/></label><label className="form-field">Field observation and verification context<Textarea name="comment" required placeholder="Record how the equipment was identified and what was checked."/></label><Button type="submit" loading={busy}>Save field reading</Button><p className="form-help">The reading is traceable to your account. Resolve or escalate the related report separately.</p></form></DialogPanel></DialogPopup></Dialog>;
}
export function HistoryList({ equipmentId }: { equipmentId: string }) {
  const { state } = useHub(); const rows = state.history.filter(h => h.equipmentId === equipmentId);
  return <><div className="section-intro"><p className="eyebrow">FAILURE MEMORY</p><h2>What happened before</h2><p>Historical causes are evidence for investigation, not a diagnosis of the current condition.</p></div>{state.cases.filter(c => c.equipmentId === equipmentId).map(c => <Link className="history-item" key={c.id} href={`/cases/${c.id}`}><Status tone={c.status === "verified_closed" ? "green" : "amber"}>{c.status.replaceAll("_", " ")}</Status><strong>{c.title}</strong><small>{formatDate(c.observedAt)} · {c.reporter}</small></Link>)}{rows.map(h => <Link className="history-item" key={h.id} href={`/cases/${h.id}`}><span className="history-date">{formatDate(h.date)} <span>{h.type}</span></span><strong>{h.symptom}</strong><span className="mono small">{h.wo}<ArrowUpRight size={13}/></span></Link>)}{!rows.length && <Empty title="No imported history">Maintenance records have not been imported.</Empty>}</>;
}
